CREATE TABLE `user_gift` (
  `user_id` VARCHAR(255) NOT NULL,
  `gift_id` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;